//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


public class ProjectDilemmaCatalog
{
    public class Items
    {
        public class emote_wave
        {
            public const string key = "emote_wave";
            public class StaticProperties
            {
                public const string int_value = "int_value";
                public const string double_value = "double_value";
                public const string bool_value = "bool_value";
                public const string parameter_type = "parameter_type";
                public const string animation_parameter = "animation_parameter";
                public const string description = "description";
                public const string ingame_ScriptableObject = "ingame_ScriptableObject";
                public const string inventory_icon = "inventory_icon";
            }
            public class Properties
            {
                public const string equipped = "equipped";
                public const string newlyAdded = "newlyAdded";
            }
        }
        public class ability_magnifyingGlass
        {
            public const string key = "ability_magnifyingGlass";
            public class StaticProperties
            {
                public const string description = "description";
                public const string number_of_games = "number_of_games";
                public const string ingame_ScriptableObject = "ingame_ScriptableObject";
                public const string inventory_icon = "inventory_icon";
            }
            public class Properties
            {
                public const string equipped = "equipped";
                public const string newlyAdded = "newlyAdded";
            }
        }
        public class throwable_egg
        {
            public const string key = "throwable_egg";
            public class StaticProperties
            {
                public const string description = "description";
                public const string ingame_ScriptableObject = "ingame_ScriptableObject";
                public const string inventory_icon = "inventory_icon";
            }
            public class Properties
            {
                public const string equipped = "equipped";
                public const string newlyAdded = "newlyAdded";
            }
        }
        public class throwable_rose
        {
            public const string key = "throwable_rose";
            public class StaticProperties
            {
                public const string description = "description";
                public const string ingame_ScriptableObject = "ingame_ScriptableObject";
                public const string inventory_icon = "inventory_icon";
            }
            public class Properties
            {
                public const string equipped = "equipped";
                public const string newlyAdded = "newlyAdded";
            }
        }
        public class throwable_waterbaloon
        {
            public const string key = "throwable_waterbaloon";
            public class StaticProperties
            {
                public const string description = "description";
                public const string ingame_ScriptableObject = "ingame_ScriptableObject";
                public const string inventory_icon = "inventory_icon";
            }
            public class Properties
            {
                public const string equipped = "equipped";
                public const string newlyAdded = "newlyAdded";
            }
        }
        public class throwable_tomato
        {
            public const string key = "throwable_tomato";
            public class StaticProperties
            {
                public const string description = "description";
                public const string ingame_ScriptableObject = "ingame_ScriptableObject";
                public const string inventory_icon = "inventory_icon";
            }
            public class Properties
            {
                public const string equipped = "equipped";
                public const string newlyAdded = "newlyAdded";
            }
        }
        public class throwable_cupcake
        {
            public const string key = "throwable_cupcake";
            public class StaticProperties
            {
                public const string description = "description";
                public const string ingame_ScriptableObject = "ingame_ScriptableObject";
                public const string inventory_icon = "inventory_icon";
            }
            public class Properties
            {
                public const string equipped = "equipped";
                public const string newlyAdded = "newlyAdded";
            }
        }
        public class emote_angry
        {
            public const string key = "emote_angry";
            public class StaticProperties
            {
                public const string int_value = "int_value";
                public const string double_value = "double_value";
                public const string bool_value = "bool_value";
                public const string parameter_type = "parameter_type";
                public const string animation_parameter = "animation_parameter";
                public const string description = "description";
                public const string ingame_ScriptableObject = "ingame_ScriptableObject";
                public const string inventory_icon = "inventory_icon";
            }
            public class Properties
            {
                public const string equipped = "equipped";
                public const string newlyAdded = "newlyAdded";
            }
        }
        public class emote_flex
        {
            public const string key = "emote_flex";
            public class StaticProperties
            {
                public const string int_value = "int_value";
                public const string double_value = "double_value";
                public const string bool_value = "bool_value";
                public const string parameter_type = "parameter_type";
                public const string animation_parameter = "animation_parameter";
                public const string description = "description";
                public const string ingame_ScriptableObject = "ingame_ScriptableObject";
                public const string inventory_icon = "inventory_icon";
            }
            public class Properties
            {
                public const string equipped = "equipped";
                public const string newlyAdded = "newlyAdded";
            }
        }
        public class emote_cry
        {
            public const string key = "emote_cry";
            public class StaticProperties
            {
                public const string int_value = "int_value";
                public const string double_value = "double_value";
                public const string bool_value = "bool_value";
                public const string parameter_type = "parameter_type";
                public const string animation_parameter = "animation_parameter";
                public const string description = "description";
                public const string ingame_ScriptableObject = "ingame_ScriptableObject";
                public const string inventory_icon = "inventory_icon";
            }
            public class Properties
            {
                public const string equipped = "equipped";
                public const string newlyAdded = "newlyAdded";
            }
        }
        public class emote_kiss
        {
            public const string key = "emote_kiss";
            public class StaticProperties
            {
                public const string int_value = "int_value";
                public const string double_value = "double_value";
                public const string bool_value = "bool_value";
                public const string parameter_type = "parameter_type";
                public const string animation_parameter = "animation_parameter";
                public const string description = "description";
                public const string ingame_ScriptableObject = "ingame_ScriptableObject";
                public const string inventory_icon = "inventory_icon";
            }
            public class Properties
            {
                public const string equipped = "equipped";
                public const string newlyAdded = "newlyAdded";
            }
        }
        public class cosmetic_bearMask
        {
            public const string key = "cosmetic_bearMask";
            public class StaticProperties
            {
                public const string description = "description";
                public const string ingame_ScriptableObject = "ingame_ScriptableObject";
                public const string inventory_icon = "inventory_icon";
            }
            public class Properties
            {
                public const string equipped = "equipped";
                public const string newlyAdded = "newlyAdded";
            }
        }
        public class cosmetic_cargoPants
        {
            public const string key = "cosmetic_cargoPants";
            public class StaticProperties
            {
                public const string description = "description";
                public const string ingame_ScriptableObject = "ingame_ScriptableObject";
                public const string inventory_icon = "inventory_icon";
            }
            public class Properties
            {
                public const string equipped = "equipped";
                public const string newlyAdded = "newlyAdded";
            }
        }
        public class cosmetic_dobermanMask
        {
            public const string key = "cosmetic_dobermanMask";
            public class StaticProperties
            {
                public const string description = "description";
                public const string ingame_ScriptableObject = "ingame_ScriptableObject";
                public const string inventory_icon = "inventory_icon";
            }
            public class Properties
            {
                public const string equipped = "equipped";
                public const string newlyAdded = "newlyAdded";
            }
        }
        public class cosmetic_hoodie
        {
            public const string key = "cosmetic_hoodie";
            public class StaticProperties
            {
                public const string description = "description";
                public const string ingame_ScriptableObject = "ingame_ScriptableObject";
                public const string inventory_icon = "inventory_icon";
            }
            public class Properties
            {
                public const string equipped = "equipped";
                public const string newlyAdded = "newlyAdded";
            }
        }
        public class cosmetic_jeans
        {
            public const string key = "cosmetic_jeans";
            public class StaticProperties
            {
                public const string description = "description";
                public const string ingame_ScriptableObject = "ingame_ScriptableObject";
                public const string inventory_icon = "inventory_icon";
            }
            public class Properties
            {
                public const string equipped = "equipped";
                public const string newlyAdded = "newlyAdded";
            }
        }
        public class cosmetic_jockJacker
        {
            public const string key = "cosmetic_jockJacker";
            public class StaticProperties
            {
                public const string description = "description";
                public const string ingame_ScriptableObject = "ingame_ScriptableObject";
                public const string inventory_icon = "inventory_icon";
            }
            public class Properties
            {
                public const string equipped = "equipped";
                public const string newlyAdded = "newlyAdded";
            }
        }
        public class cosmetic_motorcycleJacket
        {
            public const string key = "cosmetic_motorcycleJacket";
            public class StaticProperties
            {
                public const string description = "description";
                public const string ingame_ScriptableObject = "ingame_ScriptableObject";
                public const string inventory_icon = "inventory_icon";
            }
            public class Properties
            {
                public const string equipped = "equipped";
                public const string newlyAdded = "newlyAdded";
            }
        }
        public class cosmetic_owlMask
        {
            public const string key = "cosmetic_owlMask";
            public class StaticProperties
            {
                public const string description = "description";
                public const string ingame_ScriptableObject = "ingame_ScriptableObject";
                public const string inventory_icon = "inventory_icon";
            }
            public class Properties
            {
                public const string equipped = "equipped";
                public const string newlyAdded = "newlyAdded";
            }
        }
        public class cosmetic_pufferJacket
        {
            public const string key = "cosmetic_pufferJacket";
            public class StaticProperties
            {
                public const string description = "description";
                public const string ingame_ScriptableObject = "ingame_ScriptableObject";
                public const string inventory_icon = "inventory_icon";
            }
            public class Properties
            {
                public const string equipped = "equipped";
                public const string newlyAdded = "newlyAdded";
            }
        }
        public class cosmetic_rabbitMask
        {
            public const string key = "cosmetic_rabbitMask";
            public class StaticProperties
            {
                public const string description = "description";
                public const string ingame_ScriptableObject = "ingame_ScriptableObject";
                public const string inventory_icon = "inventory_icon";
            }
            public class Properties
            {
                public const string equipped = "equipped";
                public const string newlyAdded = "newlyAdded";
            }
        }
        public class cosmetic_rainCoat
        {
            public const string key = "cosmetic_rainCoat";
            public class StaticProperties
            {
                public const string description = "description";
                public const string ingame_ScriptableObject = "ingame_ScriptableObject";
                public const string inventory_icon = "inventory_icon";
            }
            public class Properties
            {
                public const string equipped = "equipped";
                public const string newlyAdded = "newlyAdded";
            }
        }
        public class cosmetic_shorts
        {
            public const string key = "cosmetic_shorts";
            public class StaticProperties
            {
                public const string description = "description";
                public const string ingame_ScriptableObject = "ingame_ScriptableObject";
                public const string inventory_icon = "inventory_icon";
            }
            public class Properties
            {
                public const string equipped = "equipped";
                public const string newlyAdded = "newlyAdded";
            }
        }
        public class cosmetic_trainerPants
        {
            public const string key = "cosmetic_trainerPants";
            public class StaticProperties
            {
                public const string description = "description";
                public const string ingame_ScriptableObject = "ingame_ScriptableObject";
                public const string inventory_icon = "inventory_icon";
            }
            public class Properties
            {
                public const string equipped = "equipped";
                public const string newlyAdded = "newlyAdded";
            }
        }
        public class perk_doubleDown
        {
            public const string key = "perk_doubleDown";
            public class StaticProperties
            {
                public const string description = "description";
                public const string ingame_ScriptableObject = "ingame_ScriptableObject";
                public const string inventory_icon = "inventory_icon";
            }
            public class Properties
            {
                public const string equipped = "equipped";
                public const string newlyAdded = "newlyAdded";
            }
        }
        public class perk_gambit
        {
            public const string key = "perk_gambit";
            public class StaticProperties
            {
                public const string description = "description";
                public const string ingame_ScriptableObject = "ingame_ScriptableObject";
                public const string inventory_icon = "inventory_icon";
            }
            public class Properties
            {
                public const string equipped = "equipped";
                public const string newlyAdded = "newlyAdded";
            }
        }
        public class perk_magicEightball
        {
            public const string key = "perk_magicEightball";
            public class StaticProperties
            {
                public const string description = "description";
                public const string ingame_ScriptableObject = "ingame_ScriptableObject";
                public const string inventory_icon = "inventory_icon";
            }
            public class Properties
            {
                public const string equipped = "equipped";
                public const string newlyAdded = "newlyAdded";
            }
        }
        public class perk_mirageOfFortune
        {
            public const string key = "perk_mirageOfFortune";
            public class StaticProperties
            {
                public const string description = "description";
                public const string ingame_ScriptableObject = "ingame_ScriptableObject";
                public const string inventory_icon = "inventory_icon";
            }
            public class Properties
            {
                public const string equipped = "equipped";
                public const string newlyAdded = "newlyAdded";
            }
        }
        public class perk_parallelInfusion
        {
            public const string key = "perk_parallelInfusion";
            public class StaticProperties
            {
                public const string description = "description";
                public const string ingame_ScriptableObject = "ingame_ScriptableObject";
                public const string inventory_icon = "inventory_icon";
            }
            public class Properties
            {
                public const string equipped = "equipped";
                public const string newlyAdded = "newlyAdded";
            }
        }
        public class perk_safeGuard
        {
            public const string key = "perk_safeGuard";
            public class StaticProperties
            {
                public const string description = "description";
                public const string ingame_ScriptableObject = "ingame_ScriptableObject";
                public const string inventory_icon = "inventory_icon";
            }
            public class Properties
            {
                public const string equipped = "equipped";
                public const string newlyAdded = "newlyAdded";
            }
        }
        public class perk_theFool
        {
            public const string key = "perk_theFool";
            public class StaticProperties
            {
                public const string description = "description";
                public const string ingame_ScriptableObject = "ingame_ScriptableObject";
                public const string inventory_icon = "inventory_icon";
            }
            public class Properties
            {
                public const string equipped = "equipped";
                public const string newlyAdded = "newlyAdded";
            }
        }
        public class perk_vigorousMind
        {
            public const string key = "perk_vigorousMind";
            public class StaticProperties
            {
                public const string description = "description";
                public const string ingame_ScriptableObject = "ingame_ScriptableObject";
                public const string inventory_icon = "inventory_icon";
            }
            public class Properties
            {
                public const string equipped = "equipped";
                public const string newlyAdded = "newlyAdded";
            }
        }
        public class perk_wheelOfFortune
        {
            public const string key = "perk_wheelOfFortune";
            public class StaticProperties
            {
                public const string description = "description";
                public const string ingame_ScriptableObject = "ingame_ScriptableObject";
                public const string inventory_icon = "inventory_icon";
            }
            public class Properties
            {
                public const string equipped = "equipped";
                public const string newlyAdded = "newlyAdded";
            }
        }
        public class cosmetic_deerMask
        {
            public const string key = "cosmetic_deerMask";
            public class StaticProperties
            {
                public const string description = "description";
                public const string ingame_ScriptableObject = "ingame_ScriptableObject";
                public const string inventory_icon = "inventory_icon";
            }
            public class Properties
            {
                public const string equipped = "equipped";
                public const string newlyAdded = "newlyAdded";
            }
        }
        public class cosmetic_defaultMask
        {
            public const string key = "cosmetic_defaultMask";
            public class StaticProperties
            {
                public const string description = "description";
                public const string ingame_ScriptableObject = "ingame_ScriptableObject";
                public const string inventory_icon = "inventory_icon";
            }
            public class Properties
            {
                public const string equipped = "equipped";
                public const string newlyAdded = "newlyAdded";
            }
        }
        public class cosmetic_defaultPants
        {
            public const string key = "cosmetic_defaultPants";
            public class StaticProperties
            {
                public const string description = "description";
                public const string ingame_ScriptableObject = "ingame_ScriptableObject";
                public const string inventory_icon = "inventory_icon";
            }
            public class Properties
            {
                public const string equipped = "equipped";
                public const string newlyAdded = "newlyAdded";
            }
        }
        public class cosmetic_kingpinVest
        {
            public const string key = "cosmetic_kingpinVest";
            public class StaticProperties
            {
                public const string description = "description";
                public const string ingame_ScriptableObject = "ingame_ScriptableObject";
                public const string inventory_icon = "inventory_icon";
            }
            public class Properties
            {
                public const string equipped = "equipped";
                public const string newlyAdded = "newlyAdded";
            }
        }
        public class cosmetic_kingpinMask
        {
            public const string key = "cosmetic_kingpinMask";
            public class StaticProperties
            {
                public const string description = "description";
                public const string ingame_ScriptableObject = "ingame_ScriptableObject";
                public const string inventory_icon = "inventory_icon";
            }
            public class Properties
            {
                public const string equipped = "equipped";
                public const string newlyAdded = "newlyAdded";
            }
        }
        public class cosmetic_kingpinPants
        {
            public const string key = "cosmetic_kingpinPants";
            public class StaticProperties
            {
                public const string description = "description";
                public const string ingame_ScriptableObject = "ingame_ScriptableObject";
                public const string inventory_icon = "inventory_icon";
            }
            public class Properties
            {
                public const string equipped = "equipped";
                public const string newlyAdded = "newlyAdded";
            }
        }
        public class cosmetic_kingpinGloves
        {
            public const string key = "cosmetic_kingpinGloves";
            public class StaticProperties
            {
                public const string description = "description";
                public const string ingame_ScriptableObject = "ingame_ScriptableObject";
                public const string inventory_icon = "inventory_icon";
            }
            public class Properties
            {
                public const string equipped = "equipped";
                public const string newlyAdded = "newlyAdded";
            }
        }
        public class cosmetic_kingpinShoes
        {
            public const string key = "cosmetic_kingpinShoes";
            public class StaticProperties
            {
                public const string description = "description";
                public const string ingame_ScriptableObject = "ingame_ScriptableObject";
                public const string inventory_icon = "inventory_icon";
            }
            public class Properties
            {
                public const string equipped = "equipped";
                public const string newlyAdded = "newlyAdded";
            }
        }
        public class relic_basicRelic
        {
            public const string key = "relic_basicRelic";
            public class StaticProperties
            {
                public const string description = "description";
                public const string ingame_ScriptableObject = "ingame_ScriptableObject";
                public const string inventory_icon = "inventory_icon";
            }
            public class Properties
            {
                public const string equipped = "equipped";
                public const string newlyAdded = "newlyAdded";
            }
        }
    }
    public class Currencies
    {
        public class currency_dilemmaPoints
        {
            public const string key = "currency_dilemmaPoints";
            public class StaticProperties
            {
                public const string hud_icon = "hud_icon";
            }
        }
        public class currency_hard
        {
            public const string key = "currency_hard";
            public class StaticProperties
            {
                public const string hud_icon = "hud_icon";
            }
        }
        public class player_xp
        {
            public const string key = "player_xp";
        }
        public class currency_rank
        {
            public const string key = "currency_rank";
        }
    }
    public class Transactions
    {
        public class transaction_packofeggs
        {
            public const string key = "transaction_packofeggs";
            public class StaticProperties
            {
                public const string transaction_icon = "transaction_icon";
                public const string item_icon = "item_icon";
                public const string promotion_badge = "promotion_badge";
                public const string repeatable = "repeatable";
            }
        }
        public class transaction_bunchOfCupcakes
        {
            public const string key = "transaction_bunchOfCupcakes";
            public class StaticProperties
            {
                public const string transaction_icon = "transaction_icon";
                public const string item_icon = "item_icon";
                public const string promotion_badge = "promotion_badge";
                public const string repeatable = "repeatable";
            }
        }
        public class transaction_bouquetOfRoses
        {
            public const string key = "transaction_bouquetOfRoses";
            public class StaticProperties
            {
                public const string transaction_icon = "transaction_icon";
                public const string item_icon = "item_icon";
                public const string promotion_badge = "promotion_badge";
                public const string repeatable = "repeatable";
            }
        }
        public class transaction_boxOfWaterBaloons
        {
            public const string key = "transaction_boxOfWaterBaloons";
            public class StaticProperties
            {
                public const string transaction_icon = "transaction_icon";
                public const string item_icon = "item_icon";
                public const string promotion_badge = "promotion_badge";
                public const string repeatable = "repeatable";
            }
        }
        public class transaction_bagOfTomatoes
        {
            public const string key = "transaction_bagOfTomatoes";
            public class StaticProperties
            {
                public const string transaction_icon = "transaction_icon";
                public const string item_icon = "item_icon";
                public const string promotion_badge = "promotion_badge";
                public const string repeatable = "repeatable";
            }
        }
        public class transaction_xp
        {
            public const string key = "transaction_xp";
            public class StaticProperties
            {
                public const string transaction_icon = "transaction_icon";
                public const string item_icon = "item_icon";
                public const string promotion_badge = "promotion_badge";
                public const string repeatable = "repeatable";
            }
        }
        public class waveEmote
        {
            public const string key = "waveEmote";
            public class StaticProperties
            {
                public const string transaction_icon = "transaction_icon";
                public const string item_icon = "item_icon";
                public const string promotion_badge = "promotion_badge";
                public const string repeatable = "repeatable";
            }
        }
        public class transaction_bearMask
        {
            public const string key = "transaction_bearMask";
            public class StaticProperties
            {
                public const string transaction_icon = "transaction_icon";
                public const string item_icon = "item_icon";
                public const string promotion_badge = "promotion_badge";
                public const string repeatable = "repeatable";
            }
        }
        public class transaction_rabbitMask
        {
            public const string key = "transaction_rabbitMask";
            public class StaticProperties
            {
                public const string transaction_icon = "transaction_icon";
                public const string item_icon = "item_icon";
                public const string promotion_badge = "promotion_badge";
                public const string repeatable = "repeatable";
            }
        }
        public class transaction_dobermanMask
        {
            public const string key = "transaction_dobermanMask";
            public class StaticProperties
            {
                public const string transaction_icon = "transaction_icon";
                public const string item_icon = "item_icon";
                public const string promotion_badge = "promotion_badge";
                public const string repeatable = "repeatable";
            }
        }
        public class transaction_owlMask
        {
            public const string key = "transaction_owlMask";
            public class StaticProperties
            {
                public const string transaction_icon = "transaction_icon";
                public const string item_icon = "item_icon";
                public const string promotion_badge = "promotion_badge";
                public const string repeatable = "repeatable";
            }
        }
        public class transaction_hoodie
        {
            public const string key = "transaction_hoodie";
            public class StaticProperties
            {
                public const string transaction_icon = "transaction_icon";
                public const string item_icon = "item_icon";
                public const string promotion_badge = "promotion_badge";
                public const string repeatable = "repeatable";
            }
        }
        public class transaction_jockJacket
        {
            public const string key = "transaction_jockJacket";
            public class StaticProperties
            {
                public const string transaction_icon = "transaction_icon";
                public const string item_icon = "item_icon";
                public const string promotion_badge = "promotion_badge";
                public const string repeatable = "repeatable";
            }
        }
        public class transaction_motorcycleJacket
        {
            public const string key = "transaction_motorcycleJacket";
            public class StaticProperties
            {
                public const string transaction_icon = "transaction_icon";
                public const string item_icon = "item_icon";
                public const string promotion_badge = "promotion_badge";
                public const string repeatable = "repeatable";
            }
        }
        public class transaction_pufferJacket
        {
            public const string key = "transaction_pufferJacket";
            public class StaticProperties
            {
                public const string transaction_icon = "transaction_icon";
                public const string item_icon = "item_icon";
                public const string promotion_badge = "promotion_badge";
                public const string repeatable = "repeatable";
            }
        }
        public class transaction_raincoat
        {
            public const string key = "transaction_raincoat";
            public class StaticProperties
            {
                public const string transaction_icon = "transaction_icon";
                public const string item_icon = "item_icon";
                public const string promotion_badge = "promotion_badge";
                public const string repeatable = "repeatable";
            }
        }
        public class transaction_jeans
        {
            public const string key = "transaction_jeans";
            public class StaticProperties
            {
                public const string transaction_icon = "transaction_icon";
                public const string item_icon = "item_icon";
                public const string promotion_badge = "promotion_badge";
                public const string repeatable = "repeatable";
            }
        }
        public class transaction_cargoPants
        {
            public const string key = "transaction_cargoPants";
            public class StaticProperties
            {
                public const string transaction_icon = "transaction_icon";
                public const string item_icon = "item_icon";
                public const string promotion_badge = "promotion_badge";
                public const string repeatable = "repeatable";
            }
        }
        public class transaction_shorts
        {
            public const string key = "transaction_shorts";
            public class StaticProperties
            {
                public const string transaction_icon = "transaction_icon";
                public const string item_icon = "item_icon";
                public const string promotion_badge = "promotion_badge";
                public const string repeatable = "repeatable";
            }
        }
        public class transaction_trainerPants
        {
            public const string key = "transaction_trainerPants";
            public class StaticProperties
            {
                public const string transaction_icon = "transaction_icon";
                public const string item_icon = "item_icon";
                public const string promotion_badge = "promotion_badge";
                public const string repeatable = "repeatable";
            }
        }
        public class transaction_angry
        {
            public const string key = "transaction_angry";
            public class StaticProperties
            {
                public const string transaction_icon = "transaction_icon";
                public const string item_icon = "item_icon";
                public const string promotion_badge = "promotion_badge";
                public const string repeatable = "repeatable";
            }
        }
        public class transaction_cry
        {
            public const string key = "transaction_cry";
            public class StaticProperties
            {
                public const string transaction_icon = "transaction_icon";
                public const string item_icon = "item_icon";
                public const string promotion_badge = "promotion_badge";
                public const string repeatable = "repeatable";
            }
        }
        public class transaction_flex
        {
            public const string key = "transaction_flex";
            public class StaticProperties
            {
                public const string transaction_icon = "transaction_icon";
                public const string item_icon = "item_icon";
                public const string promotion_badge = "promotion_badge";
                public const string repeatable = "repeatable";
            }
        }
        public class transaction_kiss
        {
            public const string key = "transaction_kiss";
            public class StaticProperties
            {
                public const string transaction_icon = "transaction_icon";
                public const string item_icon = "item_icon";
                public const string promotion_badge = "promotion_badge";
                public const string repeatable = "repeatable";
            }
        }
        public class transaction_deerMask
        {
            public const string key = "transaction_deerMask";
            public class StaticProperties
            {
                public const string transaction_icon = "transaction_icon";
                public const string item_icon = "item_icon";
                public const string promotion_badge = "promotion_badge";
                public const string repeatable = "repeatable";
            }
        }
    }
    public class Stores
    {
        public class main
        {
            public const string key = "main";
        }
    }
    public class GameParameters
    {
        public class recycler_unlock_level
        {
            public const string key = "recycler_unlock_level";
            public class StaticProperties
            {
                public const string unlock_level = "unlock_level";
            }
        }
        public class upgrader_unlock_level
        {
            public const string key = "upgrader_unlock_level";
            public class StaticProperties
            {
                public const string unlock_level = "unlock_level";
            }
        }
    }
}
